"""Mid-edit: create the optimization-parity scaffold inside the package
workspace and pre-generate the held-out parity inputs.

Two responsibilities:
  1. Create ``optimization_parity/custom_strategy.py`` — the agent's editable
     algorithm file (from ``custom_template.py``).
  2. Pre-generate the labeled training pools the agent's runner consumes.

The hidden parity secret S, the labeling function, the test-set construction,
and the metric live ONLY in ``holdout/optimization-parity/dgp.py`` (host-side,
never bind-mounted into the agent container). Here we import it host-side and
write ONLY the bit-packed training-pool LABELS into the workspace. The training
inputs themselves are pure secret-free binary noise and are regenerated by the
runner in-process from a public seed, so nothing about S (and no test labels)
ever reaches the container. Honest results are unchanged because the labels are
byte-identical to the originals.

Labels are written as base64-encoded bit-packed bytes (the create op writes
text), decoded by the runner's ``load_train_labels``. Each file covers the full
``max_train_examples`` pool; thanks to the prefix property of ``torch.randint``,
every baseline's smaller dataset is reproduced exactly by slicing.

In the Harbor verifier this module is re-imported for every evaluation by
``apply.py`` with ENV/SEED exported, so only the active run's label blobs are
materialized — and the runner deletes them after loading, before any editable
code executes (MLSBENCH_EPHEMERAL_INPUTS=1 in the eval scripts). Natively (no
ENV at workspace-setup time) every (config, seed) combination is materialized
once and kept, so repeated tests in the same workspace keep working.
"""

import base64
import json
import os
import re
import sys
from pathlib import Path

_HERE = Path(__file__).resolve()
_TASK_DIR = _HERE.parents[1]            # tasks/optimization-parity
_PROJECT_ROOT = _HERE.parents[3]        # repo root
_HOLDOUT_DIR = _PROJECT_ROOT / "holdout" / "optimization-parity"
sys.path.insert(0, str(_HOLDOUT_DIR))
import dgp  # host-only DGP + labels + metric (NOT shipped into the container)

_TEMPLATE_PATH = _HERE.parent / "custom_template.py"
_CUSTOM_PY = _TEMPLATE_PATH.read_text()

# Match the harness seed selection: task seeds if present, else default [42].
try:
    _cfg = json.loads((_TASK_DIR / "config.json").read_text())
    _SEEDS = sorted(set((_cfg.get("seeds") or []) + [42, 123, 456]))
except Exception:
    _SEEDS = [42, 123, 456]

# The (n_features, secret_size) configurations the evaluation runs. These mirror
# the scripts in tasks/optimization-parity/scripts/ (n32-k8 default, plus the
# --n-features / --secret-size overrides). Keep in sync with config.json
# test_cmds / scripts.
_CONFIGS = [
    (32, 8),   # eval.sh (defaults)
    (50, 8),   # eval_n50_k8.sh
    (64, 8),   # eval_n64_k8.sh
]

# Harbor eval-time materialization: ENV is the test label (e.g. "n50-k8";
# the default script's label is "n32-k8") and SEED the active run seed —
# materialize just the active run's blobs. Natively neither is set at
# workspace-setup time, so every combination is staged.
_ENV = os.environ.get("ENV")
_SEED = os.environ.get("SEED")
_m = re.fullmatch(r"n(\d+)-k(\d+)", _ENV or "")
if _m and (int(_m.group(1)), int(_m.group(2))) in _CONFIGS and _SEED is not None:
    _CONFIGS = [(int(_m.group(1)), int(_m.group(2)))]
    _SEEDS = [int(_SEED)]


def _config_tag(n_features, secret_size):
    return f"n{n_features}_k{secret_size}"


def _encode_labels(n_features, secret_size, seed, secret_index):
    config = dgp.make_config(n_features=n_features, secret_size=secret_size)
    packed = dgp.gen_train_labels_packed(config, seed, secret_index)
    return base64.b64encode(packed).decode("ascii")


OPS = [
    {
        "op": "create",
        "file": "pytorch-examples/optimization_parity/custom_strategy.py",
        "content": _CUSTOM_PY,
    },
]

for _n_features, _secret_size in _CONFIGS:
    _config = dgp.make_config(n_features=_n_features, secret_size=_secret_size)
    _tag = _config_tag(_n_features, _secret_size)
    for _seed in _SEEDS:
        for _si in range(_config.num_hidden_secrets):
            OPS.append({
                "op": "create",
                "file": (
                    "pytorch-examples/optimization_parity/_parity_inputs/"
                    f"{_tag}_seed{_seed}_s{_si}.labels.b64"
                ),
                "content": _encode_labels(_n_features, _secret_size, _seed, _si),
            })
